### PR TITLE
[addition][fix] Date and Link Constants, Fix Mobile Apply Button

### LINKED ISSUE #16: Application link not clickable on mobile navbar
We forgot to add the navigation link to the mobile navbar. We can quickly fix this in the future.

Image

### PR DESCRIPTION
**Pull request by dtsivkovski**
Checklist:

- [x] I have tested my changes locally and they work
- [x] My pull request targets the `main` branch of this repository.
- [x] I have organized any project files to the best of my ability

Closes #16

This pull request includes updates to centralize and utilize hackathon date information and external links across multiple components. The most important changes include the addition of a new `hackathonDateInfo` object, the use of this object in various components, and the centralization of external links.

Centralizing hackathon date information:

* [`lib/dates.ts`](diffhunk://#diff-4e882006bef42d9d2d6a27e1b24e2b38d77cd27fefb94bd3d66cb12f354ff0a4R1-R11): Added a new `hackathonDateInfo` object to define date information for the hackathon.
* [`app/(main)/_components/heading.tsx`](diffhunk://#diff-38bcb41921a40de8ae1ed55132363f783274dc56e1bb2df9643e1a6d5c4128b4R11-R12): Updated the heading component to use `hackathonDateInfo` for the hackathon year and date string. [[1]](diffhunk://#diff-38bcb41921a40de8ae1ed55132363f783274dc56e1bb2df9643e1a6d5c4128b4R11-R12) [[2]](diffhunk://#diff-38bcb41921a40de8ae1ed55132363f783274dc56e1bb2df9643e1a6d5c4128b4L124-R135)
* [`app/(main)/_components/mobileheading.tsx`](diffhunk://#diff-3b67c8ea597c94e6578d47fda1996386cbe67124784f36c91b6def5ab92b4523R5-R6): Updated the mobile heading component to use `hackathonDateInfo` for the hackathon year and date string. [[1]](diffhunk://#diff-3b67c8ea597c94e6578d47fda1996386cbe67124784f36c91b6def5ab92b4523R5-R6) [[2]](diffhunk://#diff-3b67c8ea597c94e6578d47fda1996386cbe67124784f36c91b6def5ab92b4523L13-R15) [[3]](diffhunk://#diff-3b67c8ea597c94e6578d47fda1996386cbe67124784f36c91b6def5ab92b4523L24-R26)
* [`components/footer/footer.tsx`](diffhunk://#diff-cf39e7cefe742c218198800379017a0c028629f42fbe950f0fd03ef6218dfedbR4-R9): Updated the footer component to use `hackathonDateInfo` for the hackathon year.

Centralizing external links:

* [`lib/links.ts`](diffhunk://#diff-1f959a20f72082f03d8610012eec9bdbaa51b8703c45a0485b84fe972bed7e6aR1-R5): Added a new file to define all external links used in the website.
* [`components/navbar.tsx`](diffhunk://#diff-697415f51799297bd64388e550f60789de985cb60aca6be2175bc512c9243626R9-L19): Updated the navbar component to use centralized external links from `lib/links.ts`. [[1]](diffhunk://#diff-697415f51799297bd64388e550f60789de985cb60aca6be2175bc512c9243626R9-L19) [[2]](diffhunk://#diff-697415f51799297bd64388e550f60789de985cb60aca6be2175bc512c9243626L166-R165)

### CODE REVIEW

File: components/navbar.tsx [hunk 1]
```diff
@@ -163,10 +159,10 @@ const Navbar = () => {
             Contact
           </NavLink>
           <NavLink
-            href="#"
+            href={applicationLink}
             variant={"mobile_bold"}
-            className="bg-[rgb(75,0,0)] cursor-not-allowed" // TODO: Update this when we get applying working
-            // onClick={handleMobileLinkClick}
+            className="bg-[rgb(75,0,0)]"
+            onClick={handleMobileLinkClick}
```
Comment (DylanDevelops) [inline components/navbar.tsx:165]: Let's make this open in a new tab just like the desktop apply button.
```suggestion
            onClick={handleMobileLinkClick}
            target="_blank"
```

**Review by DylanDevelops — CHANGES_REQUESTED** [review]
I just noticed one thing that needs to be fixed but once that is done, we should be good to merge.

**Comment by dtsivkovski** [comment]
I agree! I went ahead and resolved the suggestion!

**Review by DylanDevelops — APPROVED** [review]
LGTM! 👍🏼🎉
